[workspace]
members = [
    "assembler",
    "object",
    "linker",
]

[package]
name = "whale"
version = "0.1.0"
edition = "2021"

[dependencies]
assembler = { path = "assembler" }
object = { path = "object" }
